# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tutorial_nbdev',
                'doc_host': 'https://r-borgess.github.io',
                'git_url': 'https://github.com/r-borgess/tutorial_nbdev',
                'lib_path': 'tutorial_nbdev'},
  'syms': {'tutorial_nbdev.core': {'tutorial_nbdev.core.foo': ('core.html#foo', 'tutorial_nbdev/core.py')}}}
